sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build --build-arg distro=stretch -t rpi-stepmania .
# TODO: dump the output

